# -*- coding: utf-8 -*-
"""praktikum2_ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ev6b2DIQwhAYmHM6hKKQpHrp18WR8Dbz
"""

# menghubungakn colab dengan google drive
from google.colab import drive
drive.mount('/content/gdrive')

#memanggil data set lewat drive
path = "/content/gdrive/MyDrive/praktikum/praktikum2"

# membaca file csv menggunakan pandas
import pandas as pd

df=pd.read_csv(path+ '/data/datasetPraktikum2.csv')
df

# Mencari info data pada file (tipe data, non nul data, nama kolom)
df.info()

#menghitung mean semua kolom numerik
df['Height'].mean()

#menghitung median semua kolom numerik
df['Height'].median()

#menghitung modus (hati" karena bisa lebih dari satu)
df['Height'].mode()

# menghitung variansi & standar deviasi
df.var(numeric_only=True)

#menghitung standar deviasi
df.std(numeric_only=True)

# Hitung kuartil pertama (Q1)
q1 = df['Height'].quantile(0.25)
print('Q1 :' , q1)

# Hitung kuartil ketiga (Q3)
q3 = df['Height'].quantile(0.75)
print('Q3 :', q3)

# Hitung IQR (interquartile range)
iqr = q3 - q1
print('IQR :', iqr)

# untuk membuat statistika deskripsi pada type data int
df.describe()

# Menghitung matriks kolerasi untuk semua kolom numerik
correlation_matrix = df.corr(numeric_only = True)

#Menampilkan matriks kolerasi
print('Matriks Korelasi:')
print(correlation_matrix)

import pandas as pd
import numpy as np

df.boxplot(column=['Height', 'Weight'])

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Ambil data Height
data_height = df["Height"]

# Buat histogram
n, bins, patches = plt.hist(data_height, bins=5, color='grey', edgecolor='black')

# Tambahkan label
plt.title('Histogram Nilai')
plt.xlabel('Height')
plt.ylabel('Frekuensi')

# Tampilkan rentang frekuensi di sumbu x
bin_centers = 0.5 * (bins[:-1] + bins[1:])
plt.xticks(bin_centers, ['{:.0f}-{:.0f}'.format(bins[i], bins[i+1]) for i in range(len(bins)-1)])

# Tampilkan histogram
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Buat DataFrame contoh
data = {
    'Nilai1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Nilai2': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
}

df2 = pd.DataFrame(data)

# Buat scatter plot
plt.scatter(df2['Nilai1'], df2['Nilai2'], color='blue', marker='o')

# Tambahkan label
plt.title('Scatter Plot Korelasi Positif')
plt.xlabel('Nilai1')
plt.ylabel('Nilai2')

# Tambahkan grid
plt.grid(True)

# Tampilkan plot
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Buat DataFrame contoh
data = {
    'Nilai1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Nilai2': [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
}

df3 = pd.DataFrame(data)

# Buat scatter plot
plt.scatter(df3['Nilai1'], df3['Nilai2'], color='red', marker='x')

# Tambahkan label
plt.title('Scatter Plot Korelasi Negatif')
plt.xlabel('Nilai1')
plt.ylabel('Nilai2')

# Tambahkan grid
plt.grid(True)

# Tampilkan plot
plt.show()

# menghubungakn colab dengan google drive
from google.colab import drive
drive.mount('/content/gdrive')

#memanggil data set lewat drive
path = "/content/gdrive/MyDrive/praktikum/praktikum2/"

import pandas as pd
df = pd.read_csv(path+ '/data/day.csv')
df

# Mencari info data pada file (tipe data, non nul data, nama kolom)
df.info()

#menghitung mean semua kolom numerik
df['casual'].mean()

#menghitung mean semua kolom numerik
df['casual'].median()

#menghitung modus (hati" karena bisa lebih dari satu)
df['casual'].mode()

# menghitung variansi & standar deviasi
df.var(numeric_only=True)

#menghitung standar deviasi
df.std(numeric_only=True)

# Hitung kuartil pertama (Q1)
q1 = df['casual'].quantile(0.25)
print("Q1 : " , q1)

# Hitung kuartil ketiga (Q3)
q3 = df['casual'].quantile(0.75)
print("Q3 :", q3)

# Hitung IQR (interquartile range)
iqr = q3 - q1
print("IQR :", iqr)

# untuk membuat statistika deskripsi pada type data int
df.describe()

# Menghitung matriks kolerasi untuk semua kolom numerik
correlation_matrix = df.corr(numeric_only = True)

#Menampilkan matriks kolerasi
print('Matriks Korelasi:')
print(correlation_matrix)

import pandas as pd
import numpy as np

df.boxplot(column=['casual', 'mnth'])

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Ambil data casual
data_casual = df["casual"]

# Buat histogram
n, bins, patches = plt.hist(data_casual, bins=5, color='grey', edgecolor='black')

# Tambahkan label
plt.title('Histogram Nilai')
plt.xlabel('casual')
plt.ylabel('Frekuensi')

# Tampilkan rentang frekuensi di sumbu x
bin_centers = 0.5 * (bins[:-1] + bins[1:])
plt.xticks(bin_centers, ['{:.0f}-{:.0f}'.format(bins[i], bins[i+1]) for i in range(len(bins)-1)])

# Tampilkan histogram
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Buat DataFrame contoh
data = {
    'Nilai1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Nilai2': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
}

df2 = pd.DataFrame(data)

# Buat scatter plot
plt.scatter(df2['Nilai1'], df2['Nilai2'], color='blue', marker='o')

# Tambahkan label
plt.title('Scatter Plot Korelasi Positif')
plt.xlabel('Nilai1')
plt.ylabel('Nilai2')

# Tambahkan grid
plt.grid(True)

# Tampilkan plot
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Buat DataFrame contoh
data = {
    'Nilai1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Nilai2': [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
}

df3 = pd.DataFrame(data)

# Buat scatter plot
plt.scatter(df3['Nilai1'], df3['Nilai2'], color='red', marker='x')

# Tambahkan label
plt.title('Scatter Plot Korelasi Negatif')
plt.xlabel('Nilai1')
plt.ylabel('Nilai2')

# Tambahkan grid
plt.grid(True)

# Tampilkan plot
plt.show()

